### ISSUE TITLE
Workaround the broken Wifi driver

### ISSUE THREAD

**Issue by bochecha** [ideascube/ansiblecube#34]
The Ideasbox has a pretty terrible Wifi driver. The connection is very unstable.

But disabling the power management seems to help **a lot**.

Maybe at some point @mgautierfr can dust up his kernel-development skills and fix the driver, but in the meantime, this does the trick.

Basically, we'd need ansiblecube to create the `/etc/modprobe.d/rtl8723be.conf` file with this content:

```
options rtl8723be fwlps=0
```

It requires a reboot to take effect (or maybe just the right `modprobe` invocation).

This is only to be done on Ideasbox servers.

**Comment by yohanboniface** [comment]
> The Koombook (or is it the Ideasbox? no idea... @yohanboniface ?) has a pretty terrible Wifi driver.

The fix has been tested only for Ideasbox server (Peren-IT) in Bardarash, and yes fixed the issue of unstable connection between the server and an AP (we are not talking about the laptop<=>server connection).
I think this should be rolled out in all the servers with double wifi cards (maybe checking that the wifi card is the same?).

Also, the same kind of trick may help on the Koombook side, given we seem to have (at least in the RedCross one) the same issue.

**Comment by bochecha** [comment]
So on the Koombook:

```
  idVendor           0x148f Ralink Technology, Corp.
  idProduct          0x5370 RT5370 Wireless Adapter
```

Driver seems to be `rt2800usb`.

Which means the Wi-Fi issue are indeed different on the Koombook and Ideasbox.

Therefore, let me amend the initial description of this ticket to avoid confusion and make it clear that this ticket is only about the Ideasbox.

...

Done.

**Comment by bochecha** [comment]
I was suggested to use `ips=0` to make the connection stabler by Larry Finger, the maintainer of the RTL8723BE driver.

**Comment by fheslouin** [comment]
Added in commit `60fbf69`

@bochecha can you try the option `ips=0` ? If it improve the wifi stability we will had it to module.

**Comment by fheslouin** [comment]
Apparently we still have some issue, currently with one server using rtl8723be driver. 
@letompouce is going to investigate on this. Could you keep us up to date ?

**Comment by bochecha** [comment]
> @bochecha can you try the option ips=0 ? If it improve the wifi stability we will had it to module. 

I did try it, sorry for never reporting on it.

In my limited testing I didn't see any difference between using this or not using it.

**Comment by fheslouin** [comment]
`options rtl8723be fwlps=0` has been added here https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/roles/system/tasks/realtek.yml#L13

`ips=0` should be tried on rtl8723be driver
